[changelog]
header = """
# Changelog

All notable changes to this project will be documented in this file.

"""
body = """
{% for group, commits in commits | group_by(attribute="group") %}
### {{ group | upper_first }}
{% for commit in commits %}
- {{ commit.message | split(pat="\n") | first | upper_first }}
{% endfor %}
{% endfor %}
"""
trim = true

[git]
conventional_commits = false
filter_unconventional = false
split_commits = false
commit_preprocessors = [
    { pattern = "^\\[.*?\\]\\s*", replace = "" },
    { pattern = "^\\P{L}*", replace = "" },
]
commit_parsers = [
    { message = "^[Ff]eat", group = "âœ¨ Features" },
    { message = "^[Ff]ix", group = "ğŸ› Bug Fixes" },
    { message = "^[Dd]oc", group = "ğŸ“š Documentation" },
    { message = "^[Pp]erf", group = "âš¡ Performance" },
    { message = "^[Rr]efactor", group = "â™»ï¸ Refactoring" },
    { message = "^[Ss]tyle", group = "ğŸ’„ Styling" },
    { message = "^[Tt]est", skip = true },
    { message = "^[Cc]hore\\(release\\)", skip = true },
    { message = "^[Cc]hore", group = "ğŸ”§ Miscellaneous" },
    { message = "^[Bb]uild", group = "ğŸ—ï¸ Build" },
    { message = "^[Cc]i", skip = true },
    { message = "^[Uu]i", group = "ğŸ’„ Styling" },
    { body = ".*[Ss]ecurity", group = "ğŸ”’ Security" },
    { message = "^[Uu]pdate", skip = true },
    { message = "^[Dd]elete", skip = true },
    { message = "^[Cc]reate", skip = true },
    { message = "^[Aa]dd", skip = true },
    { message = "^[Mm]erge", skip = true },
    { message = "^\\[", skip = true },
    { message = ".*", group = "ğŸ“ Other Changes" },
]
protect_breaking_commits = false
filter_commits = false
tag_pattern = "v[0-9]*"
skip_tags = ""
ignore_tags = ""
topo_order = false
sort_commits = "oldest"
